[machines.nuc-intel]
hostname = "nuc-amd"
work-dir = "/root/"
user = "root"
iface = "eth0"
has-pdu = true

[apps.app1]
registry = {host = "nuc-intel"}
front = {host = "nuc-intel", port = 8081, thread = 12}

compose = [{host = "nuc-intel", nb = 12}]
text = [{host = "nuc-intel", nb = 12}]
post = [{host = "nuc-intel", nb = 12, db = "mysql1"}]
social = [{host = "nuc-intel", nb = 12, db = "file1"}]
short = [{host = "nuc-intel", nb = 12, db = "mysql1"}]
user = [{host = "nuc-intel", nb = 12, db = "mysql1"}]
timeline = [{host = "nuc-intel", nb = 12, db = "file1"}]

[apps.app2]
registry = {host = "nuc-intel"}
front = {host = "nuc-intel", port = 8082, thread = 12}

compose = [{host = "nuc-intel", nb = 12}]
text = [{host = "nuc-intel", nb = 12}]
post = [{host = "nuc-intel", nb = 12, db = "mysql2"}]
social = [{host = "nuc-intel", nb = 12, db = "file2"}]
short = [{host = "nuc-intel", nb = 12, db = "mysql2"}]
user = [{host = "nuc-intel", nb = 12, db = "mysql2"}]
timeline = [{host = "nuc-intel", nb = 12, db = "file2"}]

[apps.app3]
registry = {host = "nuc-intel"}
front = {host = "nuc-intel", port = 8083, thread = 12}

compose = [{host = "nuc-intel", nb = 12}]
text = [{host = "nuc-intel", nb = 12}]
post = [{host = "nuc-intel", nb = 12, db = "mysql3"}]
social = [{host = "nuc-intel", nb = 12, db = "file3"}]
short = [{host = "nuc-intel", nb = 12, db = "mysql3"}]
user = [{host = "nuc-intel", nb = 12, db = "mysql3"}]
timeline = [{host = "nuc-intel", nb = 12, db = "file3"}]

[apps.app4]
registry = {host = "nuc-intel"}
front = {host = "nuc-intel", port = 8084, thread = 12}

compose = [{host = "nuc-intel", nb = 12}]
text = [{host = "nuc-intel", nb = 12}]
post = [{host = "nuc-intel", nb = 12, db = "mysql4"}]
social = [{host = "nuc-intel", nb = 12, db = "file4"}]
short = [{host = "nuc-intel", nb = 12, db = "mysql4"}]
user = [{host = "nuc-intel", nb = 12, db = "mysql4"}]
timeline = [{host = "nuc-intel", nb = 12, db = "file4"}]


# Available for all services
[dbs.mysql1]
host = "nuc-intel"
port = 3309
base = "../../basic_dbs/all_10_then_3_subs_filled.sql"
kind = "mysql"

# Only timeline and social_graph works with file dbs
[dbs.file1]
host = "nuc-intel"
base = "../../basic_dbs/all_10_then_3_subs_filled.zip"
kind = "file"

# Available for all services
[dbs.mysql2]
host = "nuc-intel"
port = 3310
base = "../../basic_dbs/all_10_then_3_subs_filled.sql"
kind = "mysql"

# Only timeline and social_graph works with file dbs
[dbs.file2]
host = "nuc-intel"
base = "../../basic_dbs/all_10_then_3_subs_filled.zip"
kind = "file"

# Available for all services
[dbs.mysql3]
host = "nuc-intel"
port = 3311
base = "../../basic_dbs/all_10_then_3_subs_filled.sql"
kind = "mysql"

# Only timeline and social_graph works with file dbs
[dbs.file3]
host = "nuc-intel"
base = "../../basic_dbs/all_10_then_3_subs_filled.zip"
kind = "file"

# Available for all services
[dbs.mysql4]
host = "nuc-intel"
port = 3312
base = "../../basic_dbs/all_10_then_3_subs_filled.sql"
kind = "mysql"

# Only timeline and social_graph works with file dbs
[dbs.file4]
host = "nuc-intel"
base = "../../basic_dbs/all_10_then_3_subs_filled.zip"
kind = "file"
