[machines.ptero]
hostname = "ptero"
work-dir = "~/"
user = "root"
iface = "eth0"

[apps.app1]
registry = {host = "ptero"}
db = {host = "ptero", name = "socialNet", port = 3309, base = "./basic_dbs/zip_subs_20k.sql"}
front = {host = "ptero", port = 8081, cache = "cache1.front", thread = 12}

compose = [{host = "ptero", nb = 12}]
text = [{host = "ptero", nb = 12}]
post = [{host = "ptero", nb = 12, cache = "cache1.service"}]
social = [{host = "ptero", nb = 12, cache = "cache1.service"}]
short = [{host = "ptero", nb = 12, cache = "cache1.service"}]
user = [{host = "ptero", nb = 12, cache = "cache1.service"}]
timeline = [{host = "ptero", nb = 12<, cache = "cache1.service"}]

[caches.cache1]
host = "ptero"
size = 256
unit = "MB"
entities = {
     service = { size = 64, ttl = 100 },
     front = { size = 128 }
}
