[machines.nuc-intel]
hostname = "nuc-intel"
user = "root"
iface = "eth0"

[apps.app1]
registry = {host = "nuc-intel"}
db = {host = "nuc-intel"}
front = {host = "nuc-intel", port = 8080, cache = "cache1.front"}

compose = [{host = "nuc-intel", nb = 4, cache = "cache1.service"}]
post = [{host = "nuc-intel", nb = 4, cache = "cache1.service"}]
social = [{host = "nuc-intel", nb = 4, cache = "cache1.service"}]
text = [{host = "nuc-intel", nb = 4, cache = "cache1.service"}]
short = [{host = "nuc-intel", nb = 4, cache = "cache1.service"}]
user = [{host = "nuc-intel", nb = 4, cache = "cache1.service"}]
timeline = [{host = "nuc-intel", nb = 4, cache = "cache1.service"}]

[caches.cache1]
host = "nuc-intel"
size = 256
unit = "MB"
entities = {
     service = 64,
     front = 128
}
