nodes:
  local:
    addr: 192.168.1.17
    user: root

registry:
  node: local
  port: 7564

front:
  node: local
  actorPort: 9000
  httpPort: 8080

actors:
  all-in-one:
    node: local
    port: 9001
    services:
      dummy:
        type: DummyService
        db: mysql-1
        cache: redis-1

dbs:
  mysql-1:
    type: mysql
    node: local
    port: 3036

caches:
  redis-1:
    type: redis
    node: local
    port: 6347
