nodes:
  ptero:
    addr: 192.168.1.13
    user: root

registry:
  node: ptero
  port: 7564

front:
  node: ptero
  actorPort: 9000
  httpPort: 8080

actors:
  first:
    node: ptero
    port: 9001
    services:
      text:
        type: TextService
        db: none
      compose:
        type: ComposeService
        db: none
      posts:
        type: PostStorageService
        db: mysql-1
      users:
        type: UserService
        db: mysql-1
      urls:
        type: ShortUrlService
        db: mysql-1
      subs:
        type: SocialGraphService
        db: mysql-1
      timeline:
        type: TimelineService
        db: mysql-1
        params:
          type: sync
          batch-speed: 5000
          followers-per-page: 10000

  second:
    node: ptero
    port: 9002
    services:
      text:
        type: TextService
        db: none
      compose:
        type: ComposeService
        db: none
      posts:
        type: PostStorageService
        db: mysql-1
      users:
        type: UserService
        db: mysql-1

dbs:
  mysql-1:
    type: mysql
    node: ptero
    port: 3036
    scripts:
      - users
      - socialgraph
