nodes:
  ptero:
    addr: 192.168.1.13
    user: root

registry:
  node: ptero
  port: 7564

front:
  node: ptero
  actorPort: 9000
  httpPort: 8080

actors:
  all-in-one:
    node: ptero
    port: 9001
    services:
      posts:
        type: PostStorageService
        db: mysql-1
        cache: redis-1

dbs:
  mysql-1:
    type: mysql
    node: ptero
    port: 3036
    scripts:
      - users
      - socialgraph

caches:
  redis-1:
    type: redis
    node: ptero
    port: 6347
