Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.ssh.forward_agent = true
  config.vm.provider "virtualbox" do |v|
    v.memory = 8192
    v.cpus = 4
  end

  # Mount cachecache directories
  config.vm.synced_folder "../cachecache", "/home/vagrant/cachecache", type: "rsync",
    rsync__exclude: ["CacheLib/", ".build/"]

  # Fetch github rsa public key
  config.vm.provision "shell", privileged: false, inline: "ssh-keyscan -t rsa github.com >> /home/vagrant/.ssh/known_hosts"

  # Install dependencies
  config.vm.provision "shell", inline: "apt-get update"
  config.vm.provision "shell", inline: "apt-get install -y nlohmann-json3-dev libssh-dev libgc-dev"

  # build cachelib
  config.vm.provision "shell", privileged: false, inline: "cd cachecache; /home/vagrant/cachecache/clone_cachelib.sh"
  config.vm.provision "shell", privileged: false, inline: "cd cachecache; /home/vagrant/cachecache/build.sh" 
end
