compiler = "gyc"
libraries = ["mysqlclient", "jwt"]
description = "A minimal Ymir app"
version = "0.1.0"
name = "socialNet"
license = "proprietary"
type = "executable"
authors = ["Emile Cadorel <ecadorel@gmail.com>"]

[registry]
local = "/home/emile/.local/gyllir/socialNet"
