# Configuration of the actor system
# @optional
[sys]
addr = "0.0.0.0" # accepted connections
port = 0 # port of the tcp server
instances = 2 # number of cache instances to spawn
# nb-threads = 1 # number of threads in the system (-1 means nb cpu cores), only one required
log-lvl = "debug" # log level, info, debug, etc.
export-traces = "./entity-traces"

# Connection to the supervisor
# @mandatory
[supervisor]
addr = "127.0.0.1" # address of the actor system managing the host
port = 0 # its port, 0 will read to super_port file

# server avaible for clients
# @optional
[service]
addr = "0.0.0.0" # accepted connections
port = 6693 # port of the tcp server

# Configure cache entity default values
# @optional
[cache]
ttl = 100
size = 32
unit = "MB"
