[auth]
secret = "password"
issuer = "auth0"

[sys]
port = 0
iface = "lo"
log-lvl = "debug"
threads = 100

[registry]
name = "registry"
addr = "localhost"
port = 0

[services.user]
nb = 1
db = "mysql"
cache = "fst"

[services.timeline]
nb = 1
db = "mysql"
cache = "fst"

[services.short]
nb = 1
db = "mysql"

[services.social]
nb = 1
db = "mysql"
cache = "fst"

[services.post]
nb = 1
db = "mysql"
cache = "fst"

[services.compose]
nb = 1

[services.text]
nb = 1

[db.mysql]
name = "socialNet"
addr = "192.168.1.12"
user = "root"
pass = ""
port = 3309

[cache.fst]
addr="192.168.1.12"
port = 53173
