[auth]
secret = "password"
issuer = "auth0"

[sys]
port = 0
iface = "lo"
log-lvl = "debug"
threads = 24

[registry]
name = "registry"
addr = "localhost"
port = 0

[services.user]
nb = 12
db = "mysql"
cache = "fst"

[services.timeline]
nb = 12
db = "mysql"
cache = "fst"

[services.short]
nb = 12
db = "mysql"

[services.social]
nb = 12
db = "mysql"
cache = "fst"

[services.post]
nb = 12
db = "mysql"
cache = "fst"

[services.compose]
nb = 12

[services.text]
nb = 12

[db.mysql]
name = "socialNet"
addr = "127.0.0.1"
user = "root"
pass = ""

[cache.fst]
addr="localhost"
port = 6694
