[auth]
secret = "password"
issuer = "auth0"

[sys]
port = 0
iface = "lo"
log-lvl = "debug"

[registry]
name = "registry"
addr = "localhost"
port = 0

[db]
name = "socialNet"
addr = "192.168.1.17"
user = "root"
pass = ""

[services.user]
nb = 10

[services.timeline]
nb = 1

[services.short]
nb = 10

[services.text]
nb= 1

[services.social]
nb = 10

[services.compose]
nb = 1

[services.post]
nb = 10
