[auth]
secret = "password"
issuer = "auth0"

[sys]
port = 0
iface = "lo"
log-lvl = "debug"

[registry]
name = "registry"
addr = "localhost"
port = 0

[services.user]
nb = 4
db = "mysql"
#cache = "fst"

[services.timeline]
nb = 4
db = "mysql"

[services.short]
nb = 1
db = "mysql"

[services.social]
nb = 4
db = "mysql"

[services.post]
nb = 4
db = "mysql"
#cache = "fst"

[services.compose]
nb = 4
#cache = "fst"

[services.text]
nb = 4

[db.mysql]
name = "socialNet"
addr = "127.0.0.1"
user = "root"
pass = ""

# [cache.fst]
# addr="localhost"
# port = 6650
