# Configuration of the actor system
# @optional
[sys]
addr = "0.0.0.0" # accepted connections
port = 0 # port of the tcp server, 0 will write to super port file
freq = 1
# nb-threads = 1 # number of threads in the system (-1 means nb cpu cores), only one required
log-lvl = "debug" # log level, info, debug, etc.
export-traces = "./super-traces" # the file in which market traces are exported in json

# Configuration of the memory pool
# @optional
[cache]
size = 256 # amount of memory usable by the pool in MB
unit = "MB"
