[machines.dahu-4]
hostname = "dahu-4.grenoble.g5k"
user = "root"
installer = ["./install/configure.sh", "./install/http.sh", "./install/rdUtils.sh", "./install/socialNet.sh"]

[machines.dahu-5]
hostname = "dahu-5.grenoble.g5k"
user = "root"
installer = ["./install/configure.sh", "./install/http.sh", "./install/rdUtils.sh", "./install/socialNet.sh"]

[machines.dahu-6]
hostname = "dahu-6.grenoble.g5k"
user = "root"
installer = ["./install/configure.sh", "./install/http.sh", "./install/rdUtils.sh", "./install/socialNet.sh"]

[machines.dahu-7]
hostname = "dahu-7.grenoble.g5k"
user = "root"
installer = ["./install/configure.sh", "./install/http.sh", "./install/rdUtils.sh", "./install/socialNet.sh"]

[machines.dahu-8]
hostname = "dahu-8.grenoble.g5k"
user = "root"
installer = ["./install/configure.sh", "./install/http.sh", "./install/rdUtils.sh", "./install/socialNet.sh"]

[machines.dahu-9]
hostname = "dahu-9.grenoble.g5k"
user = "root"
installer = ["./install/configure.sh", "./install/http.sh", "./install/rdUtils.sh", "./install/socialNet.sh"]

[machines.dahu-31]
hostname = "dahu-31.grenoble.g5k"
user = "root"
installer = ["./install/configure.sh", "./install/http.sh", "./install/rdUtils.sh", "./install/socialNet.sh"]

[machines.dahu-32]
hostname = "dahu-32.grenoble.g5k"
user = "root"
installer = ["./install/configure.sh", "./install/rdUtils.sh", "./install/cache.sh"]
