[machines.nuc-intel]
hostname = "nuc-intel"
user = "root"
iface = "eth0"

[deploy.app1]
registry = {host = "nuc-intel"}
bdd = {host = "nuc-intel"}
front = {host = "nuc-intel", port = 8080, cache = "front"}

compose = [{host = "nuc-intel", nb = 4, cache = "service"}]
post = [{host = "nuc-intel", nb = 4, cache = "service"}]
social = [{host = "nuc-intel", nb = 4, cache = "service"}]
text = [{host = "nuc-intel", nb = 4, cache = "service"}]
short = [{host = "nuc-intel", nb = 4, cache = "service"}]
user = [{host = "nuc-intel", nb = 4, cache = "service"}]
timeline = [{host = "nuc-intel", nb = 4, cache = "service"}]

[deploy.app1.cache]
host = "nuc-intel"
size = 256
unit = "MB"
entities = {
     service = 64,
     front = 128
}
