[machines.nuc-intel]
hostname = "nuc-intel"
work-dir = "/tmp/tests1"
user = "root"
iface = "eth0"
has-pdu = true

[apps.app1]
registry = {host = "nuc-intel"}
front = {host = "nuc-intel", port = 8081, cache = "cache1.front", thread = 24}

compose = [{host = "nuc-intel", nb = 1}]
text = [{host = "nuc-intel", nb = 1}]
post = [{host = "nuc-intel", nb = 1, cache = "cache1.service", db = "mysql"}]
social = [{host = "nuc-intel", nb = 1, cache = "cache1.service", db = "file"}]
short = [{host = "nuc-intel", nb = 1, cache = "cache1.service", db = "mysql"}]
user = [{host = "nuc-intel", nb = 1, cache = "cache1.service", db = "mysql"}]
timeline = [{host = "nuc-intel", nb = 1, cache = "cache1.service", db = "file"}]

[dbs.mysql]
host = "nuc-intel"
port = 3309
base = "./basic_dbs/zip_subs_20k.sql"
kind = "mysql"

[dbs.file]
host = "nuc-intel"
base = "./basic_dbs/zip_subs_20k.zip"
kind = "file"

[caches.cache1]
host = "nuc-intel"
version = "disk"
size = 0
unit = "MB"
entities = {
     service = { size = 64, ttl = 100 },
     front = { size = 128 }
}
