[machines.nuc-intel]
hostname = "nuc-intel"
work-dir = "/tmp/tests1"
user = "root"
iface = "eth0"
has-pdu = true

[apps.app1]
registry = {host = "nuc-intel"}
db = {host = "nuc-intel", name = "socialNet", port = 3309, base = "./basic_dbs/zip_subs_20k.sql" }
front = {host = "nuc-intel", port = 8081, threads = 1}#, cache = "cache1.front"}

compose = [{host = "nuc-intel", nb = 1}]
text = [{host = "nuc-intel", nb = 1}]
post = [{host = "nuc-intel", nb = 1}]#, cache = "cache1.service"}]
social = [{host = "nuc-intel", nb = 1}]#, cache = "cache1.service"}]
short = [{host = "nuc-intel", nb = 1}]#, cache = "cache1.service"}]
user = [{host = "nuc-intel", nb = 1}]#, cache = "cache1.service"}]
timeline = [{host = "nuc-intel", nb = 1}]#, cache = "cache1.service"}]

# [caches.cache1]
# host = "nuc-intel"
# size = 256
# unit = "MB"
# entities = {
#      service = { size = 64, ttl = 100 },
#      front = { size = 18 }
# }
